import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import outputs from '../../amplify_outputs.json';
import type { Schema } from '../../amplify/data/resource';

/** Strictly-typed Apps table schema (mirrors `amplify/data/resource.ts`). */
export type { Schema };

/**
 * Central Amplify configuration. Consumes the backend outputs generated by
 * the Amplify CLI (`npx ampx sandbox` / deploy). Import this module first so
 * every subsequent auth/data/storage call is configured.
 */
Amplify.configure(outputs);

/** Typed Data client for CRUDL operations against the backend schema. */
export const dataClient = generateClient<Schema>();